spring:
  application:
    name: chat
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: chatdev
    password: chatdev
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: ConnectionPool
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 60000 # 1분
      connection-timeout: 30000 # 30초
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      repositories:
        enabled: false