package cwchoiit.chat.push.constants;

public interface MessageType {
    String INVITE_RESPONSE = "INVITE_RESPONSE";
    String ACCEPT_RESPONSE = "ACCEPT_RESPONSE";
    String REJECT_RESPONSE = "REJECT_RESPONSE";
    String DISCONNECT_RESPONSE = "DISCONNECT_RESPONSE";
    String CHANNEL_CREATE_RESPONSE = "CHANNEL_CREATE_RESPONSE";
    String LEAVE_CHANNEL_RESPONSE = "LEAVE_CHANNEL_RESPONSE";
    String QUIT_CHANNEL_RESPONSE = "QUIT_CHANNEL_RESPONSE";

    String MESSAGE = "MESSAGE";
    String NOTIFY_ACCEPT = "NOTIFY_ACCEPT";
    String NOTIFY_CHANNEL_JOIN = "NOTIFY_JOIN";
    String ASK_INVITE = "ASK_INVITE";
}
