package cwchoiit.chat.client.constants;

public interface MessageType {
    // Client <-> Server
    String INVITE_REQUEST = "INVITE_REQUEST";
    String INVITE_RESPONSE = "INVITE_RESPONSE";

    String FETCH_USER_INVITE_CODE_REQUEST = "FETCH_USER_INVITE_CODE_REQUEST";
    String FETCH_USER_INVITE_CODE_RESPONSE = "FETCH_USER_INVITE_CODE_RESPONSE";

    String FETCH_CONNECTIONS_REQUEST = "FETCH_CONNECTIONS_REQUEST";
    String FETCH_CONNECTIONS_RESPONSE = "FETCH_CONNECTIONS_RESPONSE";

    String ACCEPT_REQUEST = "ACCEPT_REQUEST";
    String ACCEPT_RESPONSE = "ACCEPT_RESPONSE";

    String MESSAGE = "MESSAGE";

    String REJECT_REQUEST = "REJECT_REQUEST";
    String REJECT_RESPONSE = "REJECT_RESPONSE";

    String DISCONNECT_REQUEST = "DISCONNECT_REQUEST";
    String DISCONNECT_RESPONSE = "DISCONNECT_RESPONSE";

    String CHANNEL_CREATE_REQUEST = "CHANNEL_CREATE_REQUEST";
    String CHANNEL_CREATE_RESPONSE = "CHANNEL_CREATE_RESPONSE";

    String ENTER_CHANNEL_REQUEST = "ENTER_CHANNEL_REQUEST";
    String ENTER_CHANNEL_RESPONSE = "ENTER_CHANNEL_RESPONSE";

    // Notification
    String KEEP_ALIVE = "KEEP_ALIVE";
    String NOTIFY_ACCEPT = "NOTIFY_ACCEPT";
    String NOTIFY_CHANNEL_JOIN = "NOTIFY_JOIN";
    String ASK_INVITE = "ASK_INVITE";
    String ERROR = "ERROR";

}
