spring:
  config:
    activate:
      on-profile: local
  application:
    name: chat-push
  kafka:
    bootstrap-servers: localhost:19094,localhost:19095,localhost:19096
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest
      properties:
        allow.auto.create.topics: false
        partition.assignment.strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor

chat-push:
  kafka:
    listeners:
      push:
        topic: push-notification
        group-id: push-group
        concurrency: 3 # 서버 하나당 3개의 쓰레드를 만들어 서버 하나로도 3개의 파티션을 처리한다.